### ISSUE TITLE
Add save_to_json method

### ISSUE THREAD

**Issue by ghost** [modsim/CADET-Python#1]
Sometimes it might be advantageous to save the input config of a CADET simulation to json instead of h5. 

Currently, the CADET class inherits from the H5 class. This would have to be restructured.

A suggestion:

CADET is only responsible for storing the data which can be saved and loaded through an interface which is implemented by an H5/Json/... class. The format could be passed as an optional argument in the save/load method with H5 as the default to provide backwards compatibility.

**Comment by schmoelder** [comment]
Just for clarification, I accidentally posted this issue with an old user account of mine (chromapy) which I have deleted in the meantime.

**Comment by Immudzen** [comment]
v0.4 can now read and write JSON files and it should fix this issue
